<svg
	xmlns="http://www.w3.org/2000/svg"
	aria-label="shadcn"
	viewBox="0 0 256 256"
	class="size-8"
	fill="none"
	stroke="currentColor"
	style="--darkreader-inline-stroke: currentColor;"
	data-darkreader-inline-stroke=""
	><line
		x1="208"
		y1="128"
		x2="128"
		y2="208"
		fill="none"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width="16"
		style="--darkreader-inline-stroke: currentColor;"
		data-darkreader-inline-stroke=""
	></line><line
		x1="192"
		y1="40"
		x2="40"
		y2="192"
		fill="none"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width="16"
		style="--darkreader-inline-stroke: currentColor;"
		data-darkreader-inline-stroke=""
	></line></svg
>
